baseURL = "https://wearefar.com/"
languageCode = "en-us"
title = "Websites & Web Applications - FAR"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
disableHugoGeneratorInject = true

[params]
description = 'FAR is a development studio based in Barcelona: we build tailor-made websites & web applications using the most suitable technologies - since 2008'

[[params.team]]
name = "Jordi Molins"
image = "/jordi-molins.jpg"
job_title = "Frontend Developer"
bio = "Jordi combines his design background with his experience as a programmer to offer global solutions in web presence and online communication."
links = [
  {url = "mailto:jordi@estudifar.com", text = "jordi@estudifar.com"}
]

[[params.team]]
name = "Victor Guerrero"
image = "/victor-guerrero.jpg"
job_title = "Fullstack developer"
bio = "His engineering background encourages Victor to face every new project as an opportunity to deliver outstanding results."
links = [
  {url = "https://twitter.com/vguerrerobosch", text = "@vguerrerobosch"},
  {url = "https://vguerrerobosch.com", text = "vguerrerobosch.com"}
]
